name: mojom
version: 0.0.5
author: Chromium Authors <mojo-dev@googlegroups.com>
description: Placeholder for mojom bindings.
homepage: https://github.com/domokit/mojo
dependencies:
  path: '>=1.3.5 <2.0.0'
  args: '>=0.13.0 <1.0.0'
environment:
  sdk: '>=1.9.0 <2.0.0'
